default: &default
    class: 'SuperPoint'
    keypoint_threshold: 0.005
    nms_radius: 4    
example:
    <<: *default
    match_threshold: 0.5
    imsize: -1
hpatch:
    <<: *default
    max_keypoints: -1
    match_threshold: 0.0
    imsize: -1
inloc:
    <<: *default
    max_keypoints: 4096
    match_threshold: 0.75
    imsize: 1024
    pairs: 'pairs-query-netvlad40-temporal.txt'
    rthres: 48
    skip_matches: 20
